-- MySQL Script generated by MySQL Workbench
-- Thu Mar 25 15:18:15 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Bibliotheque
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Bibliotheque
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Bibliotheque` DEFAULT CHARACTER SET utf8 ;
USE `Bibliotheque` ;

-- -----------------------------------------------------
-- Table `Bibliotheque`.`Auteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bibliotheque`.`Auteur` (
  `idAuteur` INT NOT NULL,
  `Nom_auteur` VARCHAR(45) NULL,
  `Prenom_auteur` VARCHAR(45) NULL,
  `DateNaissance` DATE NULL,
  `DateMort` DATE NULL,
  `Nationalite` VARCHAR(45) NULL,
  PRIMARY KEY (`idAuteur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bibliotheque`.`Emprunt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bibliotheque`.`Emprunt` (
  `idEmprunt` INT NOT NULL,
  `idLivre` INT NULL,
  `idUsager` INT NULL,
  `Date_emprunt` DATE NULL,
  `Date_retour` DATE NULL,
  PRIMARY KEY (`idEmprunt`),
  INDEX `idLivre_idx` (`idLivre` ASC),
  INDEX `IdUsager_idx` (`idUsager` ASC),
  CONSTRAINT `idLivre`
    FOREIGN KEY (`idLivre`)
    REFERENCES `Bibliotheque`.`Livre` (`idLivre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `IdUsager`
    FOREIGN KEY (`idUsager`)
    REFERENCES `Bibliotheque`.`Usager` (`idUsager`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bibliotheque`.`Usager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bibliotheque`.`Usager` (
  `idUsager` INT NOT NULL,
  `Nom_usager` VARCHAR(45) NULL,
  `Prenom_usager` VARCHAR(45) NULL,
  `Telephone` VARCHAR(10) NULL,
  `Mail` VARCHAR(45) NULL,
  `Adresse` VARCHAR(45) NULL,
  `CodePostal` INT NULL,
  `Ville` VARCHAR(20) NULL,
  `Emprunt_idEmprunt` INT NOT NULL,
  PRIMARY KEY (`idUsager`, `Emprunt_idEmprunt`),
  INDEX `fk_Usager_Emprunt1_idx` (`Emprunt_idEmprunt` ASC),
  CONSTRAINT `fk_Usager_Emprunt1`
    FOREIGN KEY (`Emprunt_idEmprunt`)
    REFERENCES `Bibliotheque`.`Emprunt` (`idEmprunt`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bibliotheque`.`Livre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bibliotheque`.`Livre` (
  `idLivre` INT NOT NULL,
  `Genre` VARCHAR(45) NULL,
  `Titre` VARCHAR(45) NULL,
  `idAuteur` INT NULL,
  `Description` VARCHAR(45) NULL,
  `Nature` VARCHAR(45) NULL,
  `Langue` VARCHAR(45) NULL,
  `Editeur` VARCHAR(45) NULL,
  `Usager_idUsager` INT NOT NULL,
  PRIMARY KEY (`idLivre`),
  INDEX `idAuteur_idx` (`idAuteur` ASC),
  INDEX `fk_Livre_Usager1_idx` (`Usager_idUsager` ASC),
  CONSTRAINT `idAuteur`
    FOREIGN KEY (`idAuteur`)
    REFERENCES `Bibliotheque`.`Auteur` (`idAuteur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Livre_Usager1`
    FOREIGN KEY (`Usager_idUsager`)
    REFERENCES `Bibliotheque`.`Usager` (`idUsager`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bibliotheque`.`Livre_has_Auteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bibliotheque`.`Livre_has_Auteur` (
  `Livre_idLivre` INT NOT NULL,
  `Auteur_idAuteur` INT NOT NULL,
  PRIMARY KEY (`Livre_idLivre`, `Auteur_idAuteur`),
  INDEX `fk_Livre_has_Auteur_Auteur1_idx` (`Auteur_idAuteur` ASC),
  INDEX `fk_Livre_has_Auteur_Livre1_idx` (`Livre_idLivre` ASC),
  CONSTRAINT `fk_Livre_has_Auteur_Livre1`
    FOREIGN KEY (`Livre_idLivre`)
    REFERENCES `Bibliotheque`.`Livre` (`idLivre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Livre_has_Auteur_Auteur1`
    FOREIGN KEY (`Auteur_idAuteur`)
    REFERENCES `Bibliotheque`.`Auteur` (`idAuteur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bibliotheque`.`Emprunt_has_Livre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bibliotheque`.`Emprunt_has_Livre` (
  `Emprunt_idEmprunt` INT NOT NULL,
  `Livre_idLivre` INT NOT NULL,
  PRIMARY KEY (`Emprunt_idEmprunt`, `Livre_idLivre`),
  INDEX `fk_Emprunt_has_Livre_Livre1_idx` (`Livre_idLivre` ASC),
  INDEX `fk_Emprunt_has_Livre_Emprunt1_idx` (`Emprunt_idEmprunt` ASC),
  CONSTRAINT `fk_Emprunt_has_Livre_Emprunt1`
    FOREIGN KEY (`Emprunt_idEmprunt`)
    REFERENCES `Bibliotheque`.`Emprunt` (`idEmprunt`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Emprunt_has_Livre_Livre1`
    FOREIGN KEY (`Livre_idLivre`)
    REFERENCES `Bibliotheque`.`Livre` (`idLivre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
